### ISSUE TITLE
Backlight dimming

### ISSUE THREAD

**Issue by Sebwap** [pimoroni/displayhatmini-python#4]
Hello there !

Is there any way to manage backlight dimming ?
I've been successful at switching it in on / off  by playing with GPIO 13 status, but is there any solution to set it at half power by example ?

**Comment by bmustata** [comment]
Have a look at this sample https://github.com/pimoroni/pirate-audio/blob/master/examples/backlight-pwm.py

**Comment by Gadgetoid** [comment]
Support added in 0.0.2, with an example here - https://github.com/pimoroni/displayhatmini-python/blob/main/examples/pwm-backlight.py

It's a bit flaky on Zero 2 W due to using RPi.GPIO's soft PWM but it works.
