### ISSUE TITLE
example pygame-basic.py crashes

### ISSUE THREAD

**Issue by PaulskPt** [pimoroni/displayhatmini-python#6]
The example pygame-basic.py crashes in line 71 pygame.draw.circle...         . Expected an int but got a float.
My 'repair' is as follows:
71 pygame.draw.circle(screen, (0, 0, 0), (int(x), int(y)), r)

**Comment by Gadgetoid** [comment]
Fixed and merged, thank you!

**Comment by PaulskPt** [comment]
You're welcome!
