### ISSUE TITLE
Both pygame examples show a black screen.

### ISSUE THREAD

**Issue by tomtitherington** [pimoroni/displayhatmini-python#9]
Hello,

When I run either of the pygame examples nothing seems to be drawn to the screen. I can see that the backlight is turned on but - the screen is completely black. I've tried both the stable and unstable installs but there is no difference in output. The pong game seems to run fine. 

Output
```
$ pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Display HAT Mini: Pygame Demo
^C *nothing appears on screen*
Exiting!...
```

Python Version
```
Python 3.9.2
```
Raspbian Version
```
Bullseye
```
Firmware Version (I had to update to a prerelease to get the camera working on the [Zero 2 W on bullseye](https://forums.raspberrypi.com/viewtopic.php?t=323462&start=25))
```
Nov  1 2021 15:53:52
Copyright (c) 2012 Broadcom
version dd030fac93d836beb7c019524e6925c783605cd3 (clean) (release) (start)
```

Any ideas? 
Thanks!

**Comment by Gadgetoid** [comment]
Is this on an otherwise freshly set-up Pi?

The pre-release firmware may be a complicating factor. The first point of call should be trying without it on a fresh image.

**Comment by Gadgetoid** [comment]
Uh belay that last suggestion- just plugged in my Z2W to test some changes and I see the same black screen for the pygame demos on an older, vanilla Bullseye :grimacing:

This will be something in the plumbing between pygame and the screen or just a silly mistake, I'll look into it.

**Comment by Gadgetoid** [comment]
The magic sauce:

```
python3 -m pip install pygame --upgrade
```

Looks like the older, preinstalled (or apt) version of pygame breaks this too. I think I'll need a version check in there somewhere.

**Comment by tomtitherington** [comment]
Ah okay. Thanks for looking into this.

I'll give that update a go now!

**Comment by tomtitherington** [comment]
That was it, thanks again!

**Comment by Gadgetoid** [comment]
Added a check into the examples now. Cheers!
